"""baseline

Initial schema snapshot covering every ORM table at the point alembic became
the authoritative schema source. On a fresh install ``alembic upgrade head``
runs this revision to create the full schema, then the drift-reconciliation
revision is a no-op (its add_column calls are guarded for idempotency).

For the live ``data/platform.db`` (which already contains these tables), the
DB is stamped at the drift-reconciliation revision via ``alembic stamp`` so
this baseline never re-runs against it.

Revision ID: 58b957aa7ad0
Revises:
Create Date: 2026-04-16 22:19:12.842814
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b957aa7ad0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('institution', sa.String(length=512), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('research_summary', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggested_actions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('actions_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('composite_id', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('deadline', sa.String(length=128), nullable=True),
    sa.Column('posted_date', sa.String(length=128), nullable=True),
    sa.Column('funding_amount', sa.String(length=256), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('opportunity_status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('deadline_type', sa.String(length=32), server_default='fixed', nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_provider', sa.String(length=128), nullable=True),
    sa.Column('resource_scale', sa.String(length=32), nullable=True),
    sa.Column('allocation_details', sa.String(length=512), nullable=True),
    sa.Column('eligibility', sa.String(length=256), nullable=True),
    sa.Column('access_url', sa.String(length=2048), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fetched_for_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['fetched_for_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_composite_id'), 'opportunities', ['composite_id'], unique=True)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_table('user_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('user_email_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('opportunity_count', sa.Integer(), nullable=False),
    sa.Column('opportunity_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_history_user_id'), 'user_email_history', ['user_id'], unique=False)
    op.create_table('user_email_prefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=8), nullable=False),
    sa.Column('min_relevance_score', sa.Float(), nullable=False),
    sa.Column('deadline_lookahead_days', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_prefs_user_id'), 'user_email_prefs', ['user_id'], unique=True)
    op.create_table('user_fetch_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sources_enabled', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_search_terms', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fetch_frequency', sa.String(length=16), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fetch_config_user_id'), 'user_fetch_config', ['user_id'], unique=True)
    op.create_table('user_filter_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword_threshold', sa.Float(), nullable=False),
    sa.Column('llm_threshold', sa.Float(), nullable=False),
    sa.Column('use_llm_filter', sa.Boolean(), nullable=False),
    sa.Column('sources_enabled', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_filter_settings_user_id'), 'user_filter_settings', ['user_id'], unique=True)
    op.create_table('user_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', 'category', name='uq_user_keyword_cat')
    )
    op.create_index(op.f('ix_user_keywords_user_id'), 'user_keywords', ['user_id'], unique=False)
    op.create_table('user_opportunity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('matched_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('profile_score', sa.Float(), nullable=True),
    sa.Column('behavior_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity')
    )
    op.create_index(op.f('ix_user_opportunity_scores_opportunity_id'), 'user_opportunity_scores', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_user_opportunity_scores_user_id'), 'user_opportunity_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_opportunity_scores_user_id'), table_name='user_opportunity_scores')
    op.drop_index(op.f('ix_user_opportunity_scores_opportunity_id'), table_name='user_opportunity_scores')
    op.drop_table('user_opportunity_scores')
    op.drop_index(op.f('ix_user_keywords_user_id'), table_name='user_keywords')
    op.drop_table('user_keywords')
    op.drop_index(op.f('ix_user_filter_settings_user_id'), table_name='user_filter_settings')
    op.drop_table('user_filter_settings')
    op.drop_index(op.f('ix_user_fetch_config_user_id'), table_name='user_fetch_config')
    op.drop_table('user_fetch_config')
    op.drop_index(op.f('ix_user_email_prefs_user_id'), table_name='user_email_prefs')
    op.drop_table('user_email_prefs')
    op.drop_index(op.f('ix_user_email_history_user_id'), table_name='user_email_history')
    op.drop_table('user_email_history')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_composite_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
